import { Lesson } from '../app/models/lesson.model';

export const SAMPLE_DATA: Lesson[] = [
  {
    id: 'lesson_1760953113701_hmfnyvzyz',
    name_zh: '',
    name_vi: 'Chào hỏi',
    description: 'Bài học Chào hỏi',
    order: 1,
    categories: [
      {
        id: 'category_1760953113701_zspsb8kg4',
        lessonId: 'lesson_1760953113701_hmfnyvzyz',
        type: 'vocabulary',
        name: 'Từ vựng',
        description: 'Bài tập Từ vựng',
        order: 1,
        exercises: [
          {
            id: 'ex_1760953113701_ahqf3nmcw',
            categoryId: '',
            type: 'vocabulary',
            question: '你好',
            description: '',
            answer: 'Xin chào1',
            explanation: '',
            pinyin: 'nǐ hǎo',
          },
          {
            id: 'ex_1760953113701_qst8aufnd',
            categoryId: '',
            type: 'vocabulary',
            question: '谢谢',
            description: '',
            answer: 'Cảm ơn1',
            explanation: '',
            pinyin: 'xiè xie',
          },
        ],
      },
      {
        id: 'category_1760953113701_wsip0rrjj',
        lessonId: 'lesson_1760953113701_hmfnyvzyz',
        type: 'grammar',
        name: 'Ngữ pháp',
        description: 'Bài tập Ngữ pháp',
        order: 2,
        exercises: [
          {
            id: 'ex_1760953113701_p6fwy87o9',
            categoryId: '',
            type: 'grammar',
            question: 'Câu có động từ "是" (shì)',
            description: 'Cấu trúc câu cơ bản với động từ "là"1',
            answer: '',
            explanation:
              'Đây là một trong những cấu trúc câu cơ bản và quan trọng nhất trong tiếng Hán.',
            content:
              "Động từ '是' (shì) - 'là' được dùng để nối hai danh từ, đại từ hoặc cụm danh từ, biểu thị sự tương đồng hoặc xác định.\r\n\r\nCấu trúc cơ bản: **Chủ ngữ + 是 + Tân ngữ**.\r\n\r\nĐây là một trong những cấu trúc câu cơ bản và quan trọng nhất trong tiếng Hán. Nó tương đương với động từ \"to be\" trong tiếng Anh.\r\n\r\nCách sử dụng: Dùng để giới thiệu bản thân, nghề nghiệp, quốc tịch, hoặc xác định mối quan hệ giữa các sự vật, sự việc.\r\n\r\nDạng phủ định là '不是' (bú shì), trong đó '不' (bù) khi đứng trước một từ mang thanh 4 sẽ biến điệu thành thanh 2 (bú).\r\n\r\nPhân tích cấu trúc:\r\n- **Chủ ngữ (Subject)**: Người hoặc vật thực hiện hành động (ví dụ: 我, 他).\r\n- **Vị ngữ (Predicate)**: Phần mô tả chủ ngữ, ở đây là '是 + Tân ngữ'.\r\n- **Tân ngữ (Object)**: Đối tượng được đề cập đến (ví dụ: 法国人, 老师).\r\n\r\nĐiểm quan trọng:\r\n- Không dùng '是' với tính từ (dùng 很 thay thế)\r\n- '是' luôn đứng sau chủ ngữ và trước tân ngữ\r\n- Trong câu hỏi, thêm 吗 ở cuối câu",
            examples: [
              '我是学生 (wǒ shì xuéshēng) Tôi là học sinh',
              '他是老师 (tā shì lǎoshī) Anh ấy là giáo viên',
              '这不是书 (zhè bú shì shū) Đây không phải là sách',
              '你是中国人吗？(nǐ shì zhōngguó rén ma?) Bạn là người Trung Quốc phải không?',
            ],
          },
        ],
      },
      {
        id: 'category_1760953113701_8vnk4khpf',
        lessonId: 'lesson_1760953113701_hmfnyvzyz',
        type: 'test',
        name: 'Kiểm tra',
        description: 'Bài tập Kiểm tra',
        order: 3,
        exercises: [
          {
            id: 'ex_1760953113701_36mo2td4i',
            categoryId: '',
            type: 'multiple_choice',
            question: '你好 nghĩa là gì?1',
            description: '',
            answer: 'Xin chào',
            explanation: '你好 có nghĩa là Xin chào',
            options: ['Cảm ơn', 'Xin chào', 'Tạm biệt', 'Xin lỗi'],
          },
          {
            id: 'ex_1760953113701_npf0d4jz8',
            categoryId: '',
            type: 'input',
            question: 'Viết pinyin của từ "Cảm ơn"',
            description: '',
            answer: 'xiè xie',
            explanation: '谢谢 có pinyin là xiè xie',
            placeholder: 'Nhập pinyin...',
          },
          {
            id: 'ex_1760953113701_xrszfrivj',
            categoryId: '',
            type: 'multiple_choice',
            question: 'Từ nào dùng để chào hỏi?',
            description: '',
            answer: '你好',
            explanation: '你好 dùng để chào hỏi',
            options: ['谢谢', '你好', '再见', '对不起'],
          },
        ],
      },
      {
        id: 'category_1760953113701_x81un6995',
        lessonId: 'lesson_1760953113701_hmfnyvzyz',
        type: 'review',
        name: 'Ôn tập',
        description: 'Bài tập Ôn tập',
        order: 4,
        exercises: [
          {
            id: 'ex_1760953113701_v5ihwegyj',
            categoryId: '',
            type: 'flashcard',
            question: '你好',
            description: 'Chào hỏi thông thường',
            answer: 'Xin chào1',
            explanation: '',
            pinyin: 'nǐ hǎo',
          },
          {
            id: 'ex_1760953113701_zibb3wj6i',
            categoryId: '',
            type: 'flashcard',
            question: '谢谢',
            description: 'Diễn đạt lòng biết ơn',
            answer: 'Cảm ơn1',
            explanation: '',
            pinyin: 'xiè xie',
          },
        ],
      },
      {
        id: 'category_1760953113701_cic15th8w',
        lessonId: 'lesson_1760953113701_hmfnyvzyz',
        type: 'speaking',
        name: 'Luyện nói',
        description: 'Bài tập Luyện nói',
        order: 5,
        exercises: [
          {
            id: 'ex_1760953113701_0cr3rs55e',
            categoryId: '',
            type: 'speaking',
            question: '你好',
            description: 'Chào hỏi cơ bản',
            answer: 'Xin chào1',
            explanation: '',
            pinyin: 'nǐ hǎo',
          },
          {
            id: 'ex_1760953113701_v7el7w7vf',
            categoryId: '',
            type: 'speaking',
            question: '谢谢',
            description: 'Cảm ơn',
            answer: 'Cảm ơn',
            explanation: '',
            pinyin: 'xiè xie',
          },
        ],
      },
      {
        id: 'category_1760953113701_fujk47arz',
        lessonId: 'lesson_1760953113701_hmfnyvzyz',
        type: 'writing',
        name: 'Luyện viết',
        description: 'Bài tập Luyện viết',
        order: 6,
        exercises: [
          {
            id: 'ex_1760953113701_mx433qvh3',
            categoryId: '',
            type: 'writing',
            question: 'Luyện viết chữ "你好"1',
            description: 'Học viết chữ chào hỏi cơ bản',
            answer: '你好',
            explanation: '',
            character: '你好',
            pinyin: 'nǐ hǎo',
            meaning: 'Xin chào',
          },
          {
            id: 'ex_1760953113701_42rb2z2vg',
            categoryId: '',
            type: 'writing',
            question: 'Luyện viết chữ "你好"',
            description: 'Học viết chữ chào hỏi cơ bản',
            answer: '你好',
            explanation: '',
            character: '你好',
            pinyin: 'nǐ hǎo',
            meaning: 'Xin chào',
          },
        ],
      },
      {
        id: 'category_1760953113701_ilqmmfgpu',
        lessonId: 'lesson_1760953113701_hmfnyvzyz',
        type: 'dialogue',
        name: 'Hội thoại',
        description: 'Bài tập Hội thoại',
        order: 7,
        exercises: [],
      },
    ],
  },
];
