import { Lesson } from '../app/models/lesson.model';

export const SAMPLE_DATA: Lesson[] = [
  {
    id: 'lesson_1761712611317_fetbwjtlg',
    name_zh: '',
    name_vi: '我叫大卫',
    description: 'Bài học 我叫大卫',
    order: 1,
    categories: [
      {
        id: 'category_1761712611317_9no7kbgws',
        lessonId: 'lesson_1761712611317_fetbwjtlg',
        type: 'vocabulary',
        name: 'Từ vựng',
        description: 'Bài tập Từ vựng',
        order: 1,
        exercises: [
          {
            id: 'ex_1761712611317_t42ed9red',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '你',
            answer: 'Bạn, anh, chị (ngôi thứ 2 số ít)',
            explanation: '',
            pinyin: 'nǐ',
          },
          {
            id: 'ex_1761712611317_ml6ooulqt',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '好',
            answer: 'Tốt, khỏe',
            explanation: '',
            pinyin: 'hǎo',
          },
          {
            id: 'ex_1761712611317_vt8xjvtcb',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '我',
            answer: 'Tôi, tớ (ngôi thứ 1 số ít)',
            explanation: '',
            pinyin: 'wǒ',
          },
          {
            id: 'ex_1761712611317_jclx7md6y',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '叫',
            answer: 'Kêu, gọi, tên là',
            explanation: '',
            pinyin: 'jiào',
          },
          {
            id: 'ex_1761712611317_86gfajlt8',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '是',
            answer: 'Là',
            explanation: '',
            pinyin: 'shì',
          },
          {
            id: 'ex_1761712611317_bu4iqdwfd',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '人',
            answer: 'Người',
            explanation: '',
            pinyin: 'rén',
          },
          {
            id: 'ex_1761712611317_n7yk3s8g2',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '吗',
            answer: 'Trợ từ nghi vấn (đặt cuối câu)',
            explanation: '',
            pinyin: 'ma',
          },
          {
            id: 'ex_1761712611317_lgvct5sba',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '他',
            answer: 'Anh ấy, ông ấy, nó (ngôi thứ 3 số ít, giống đực)',
            explanation: '',
            pinyin: 'tā',
          },
          {
            id: 'ex_1761712611317_m2wn29s9g',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '不',
            answer: 'Không',
            explanation: '',
            pinyin: 'bù',
          },
          {
            id: 'ex_1761712611317_1rydw4832',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '日本',
            answer: 'Nhật Bản',
            explanation: '',
            pinyin: 'Rìběn',
          },
          {
            id: 'ex_1761712611317_pq7ri8diw',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '法国',
            answer: 'Pháp (nước Pháp)',
            explanation: '',
            pinyin: 'Fǎguó',
          },
          {
            id: 'ex_1761712611317_ir28lugzs',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '加拿大',
            answer: 'Canada',
            explanation: '',
            pinyin: 'Jiānádà',
          },
          {
            id: 'ex_1761712611317_ybfkf7q7i',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '们',
            answer: 'Hậu tố số nhiều (kết hợp với đại từ nhân xưng)',
            explanation: '',
            pinyin: 'men',
          },
          {
            id: 'ex_1761712611317_fu7t3qh2n',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '我们',
            answer: 'Chúng tôi, chúng ta',
            explanation: '',
            pinyin: 'wǒmen',
          },
          {
            id: 'ex_1761712611317_lyhuic1c7',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '你们',
            answer: 'Các bạn, các anh/chị',
            explanation: '',
            pinyin: 'nǐmen',
          },
          {
            id: 'ex_1761712611317_5a57p3ia0',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '他们',
            answer: 'Bọn họ (cả nam nữ)',
            explanation: '',
            pinyin: 'tāmen',
          },
          {
            id: 'ex_1761712611317_elpm0rdg1',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '她们',
            answer: 'Bọn họ (các cô ấy)',
            explanation: '',
            pinyin: 'tāmen',
          },
          {
            id: 'ex_1761712611317_52ok40o50',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '老师',
            answer: 'Giáo viên, thầy/cô giáo',
            explanation: '',
            pinyin: 'lǎoshī',
          },
          {
            id: 'ex_1761712611317_ux2wqnvpe',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '您',
            answer: 'Ngài, ông, bà (ngôi thứ 2 lịch sự)',
            explanation: '',
            pinyin: 'nín',
          },
          {
            id: 'ex_1761712611317_posw2feyg',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '学生',
            answer: 'Học sinh, sinh viên',
            explanation: '',
            pinyin: 'xuésheng',
          },
          {
            id: 'ex_1761712611317_jhwu6p601',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '她',
            answer: 'Cô ấy, chị ấy, bà ấy (ngôi thứ 3 số ít,',
            explanation: '',
            pinyin: 'tā',
          },
          {
            id: 'ex_1761712611317_fxm5j37mh',
            categoryId: 'category_1761712611317_9no7kbgws',
            type: 'vocabulary',
            question: '也',
            answer: 'Cũng, cũng vậy',
            explanation: '',
            pinyin: 'yě',
          },
        ],
      },
      {
        id: 'category_1761712611318_vubi87bya',
        lessonId: 'lesson_1761712611317_fetbwjtlg',
        type: 'grammar',
        name: 'Ngữ pháp',
        description: 'Bài tập Ngữ pháp',
        order: 2,
        exercises: [
          {
            id: 'ex_1761712611318_5iin4bc17',
            categoryId: 'category_1761712611318_vubi87bya',
            type: 'grammar',
            question: 'Cách dùng từ “也” (yě)',
            answer: 'Chủ ngữ + 也 + Động từ/Tính từ',
            explanation:
              'Từ "也" có nghĩa là "cũng", dùng để diễn đạt sự tương đồng về hành động hoặc trạng thái.',
            content:
              'Nó luôn đứng trước động từ hoặc tính từ, và sau chủ ngữ. Cấu trúc cơ bản: **Chủ ngữ 1 + Verb/Adj. → Chủ ngữ 2 + 也 + Verb/Adj.**. Điều này có nghĩa là sau khi một chủ thể thực hiện hành động nào đó, một chủ thể khác cũng thực hiện hành động tương tự.',
            examples: [
              '我是学生，他也是学生。(Wǒ shì xuéshēng, tā yě shì xuéshēng.) - Tôi là học sinh, anh ấy cũng là học sinh.',
              '她是老师，我也是老师。(Tā shì lǎoshī, wǒ yě shì lǎoshī.) - Cô ấy là giáo viên, tôi cũng là giáo viên.',
              '你好吗？我也好。(Nǐ hǎo ma? Wǒ yě hǎo.) - Bạn khỏe không? Tôi cũng khỏe.',
              '他们是法国人，我们也是法国人。(Tāmen shì Fǎguó rén, wǒmen yě shì Fǎguó rén.) - Họ là người Pháp, chúng tôi cũng là người Pháp.',
            ],
          },
          {
            id: 'ex_1761712611318_i6703w5b0',
            categoryId: 'category_1761712611318_vubi87bya',
            type: 'grammar',
            question: 'Câu khẳng định với “是”',
            answer: 'Chủ ngữ + 是 + Danh từ',
            explanation:
              'Đây là cấu trúc cơ bản nhất để giới thiệu, định danh hoặc xác định một sự vật, sự việc.',
            content:
              'Động từ "是" (shì) - \'là\' được dùng để nối hai danh từ, đại từ hoặc cụm danh từ, biểu thị sự tương đồng hoặc xác định. Cấu trúc cơ bản: **Chủ ngữ + 是 + Tân ngữ**.',
            examples: [
              '我是学生。 (Wǒ shì xuéshēng.) - Tôi là học sinh.',
              '他是老师。 (Tā shì lǎoshī.) - Anh ấy là giáo viên.',
              '她是人。 (Tā shì rén.) - Cô ấy là con người.',
              '我们是学生。 (Wǒmen shì xuéshēng.) - Chúng tôi là học sinh.',
              '你们是老师。 (Nǐmen shì lǎoshī.) - Các bạn là giáo viên.',
              '他们是法国人。 (Tāmen shì Fǎguó rén.) - Họ là người Pháp.',
            ],
          },
          {
            id: 'ex_1761712611318_ag5vmsk7f',
            categoryId: 'category_1761712611318_vubi87bya',
            type: 'grammar',
            question: 'Câu phủ định với “是”',
            answer: 'Chủ ngữ + 不是 + Danh từ',
            explanation:
              '“不” (bù) đứng trước “是” để tạo thành dạng phủ định. Lưu ý về biến điệu thanh: “不” thường đọc là bù (thanh 4) nhưng khi đứng trước một từ mang thanh 4 (như “是” shì) thì đọc thành bú (thanh 2).',
            content:
              'Dạng phủ định của "是" là "不是" (bú shì). Cấu trúc: **Chủ ngữ + 不是 + Tân ngữ**.',
            examples: [
              '我不是老师。 (Wǒ bú shì lǎoshī.) - Tôi không phải là giáo viên.',
              '他不是学生。 (Tā bú shì xuéshēng.) - Anh ấy không phải là học sinh.',
              '她不是日本人。 (Tā bú shì Rìběn rén.) - Cô ấy không phải là người Nhật.',
              '我们不是法国人。 (Wǒmen bú shì Fǎguó rén.) - Chúng tôi không phải là người Pháp.',
            ],
          },
          {
            id: 'ex_1761712611318_1xtu0xked',
            categoryId: 'category_1761712611318_vubi87bya',
            type: 'grammar',
            question: 'Câu hỏi với “吗”',
            answer: 'Chủ ngữ + 是 + Danh từ + 吗？',
            explanation:
              'Thêm trợ từ nghi vấn “吗” (ma) vào cuối câu trần thuật để biến nó thành câu hỏi Có/Không, mà không cần thay đổi trật tự từ.',
            content:
              'Để hỏi một câu có/không với động từ "是", chỉ cần thêm trợ từ nghi vấn "吗" vào cuối câu khẳng định. Cấu trúc: **Chủ ngữ + 是 + Tân ngữ + 吗？**',
            examples: [
              '你是学生吗？ (Nǐ shì xuéshēng ma?) - Bạn là học sinh phải không?',
              '他是老师吗？ (Tā shì lǎoshī ma?) - Anh ấy là giáo viên phải không?',
              '您是法国人吗？ (Nín shì Fǎguó rén ma?) - Ngài là người Pháp phải không?',
              '他们是日本人吗？ (Tāmen shì Rìběn rén ma?) - Họ là người Nhật phải không?',
            ],
          },
          {
            id: 'ex_1761712611318_hromhme8m',
            categoryId: 'category_1761712611318_vubi87bya',
            type: 'grammar',
            question: 'Lưu ý: Không dùng “是” với tính từ',
            answer: 'Chủ ngữ + 很 + Tính từ',
            explanation:
              "“是” là động từ nối, KHÔNG phải trợ động từ. Nó không được dùng trước tính từ. Để diễn tả ý nghĩa tương tự với tính từ, người ta thường dùng “很” (hěn) - 'rất', dù đôi khi nó đã mờ nghĩa chỉ mức độ.",
            content:
              'Một lỗi sai phổ biến là dùng "是" trước tính từ (ví dụ: 我是好 - Sai). "是" chỉ dùng để nối với danh từ hoặc đại từ. Với tính từ, hãy sử dụng trạng từ như "很" (hěn). Cấu trúc: **Chủ ngữ + 很 + Tính từ**.',
            examples: [
              '我很好。 (Wǒ hěn hǎo.) - Tôi (rất) khỏe.',
              '他很好。 (Tā hěn hǎo.) - Anh ấy (rất) tốt.',
            ],
          },
        ],
      },
      {
        id: 'category_1761712611318_ngonv7dgl',
        lessonId: 'lesson_1761712611317_fetbwjtlg',
        type: 'test',
        name: 'Kiểm tra',
        description: 'Bài tập Kiểm tra',
        order: 3,
        exercises: [
          {
            id: 'ex_1761712611318_7j7sfh500',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“你” nghĩa là gì?',
            answer: 'Bạn, anh, chị',
            explanation: '“你” (nǐ) là đại từ nhân xưng ngôi thứ 2 số ít.',
            options: ['Tốt, khỏe', 'Tôi, tớ', 'Bạn, anh, chị', 'Là'],
          },
          {
            id: 'ex_1761712611318_za4vh4ay3',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“好” nghĩa là gì?',
            answer: 'Tốt, khỏe',
            explanation: '“好” (hǎo) có nghĩa là tốt hoặc khỏe.',
            options: ['Tốt, khỏe', 'Kêu, gọi, tên là', 'Người', 'Cũng'],
          },
          {
            id: 'ex_1761712611318_wgdpacwql',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“我” có nghĩa là gì?',
            answer: 'Tôi, tớ',
            explanation: '“我” (wǒ) là đại từ nhân xưng ngôi thứ 1 số ít.',
            options: ['Tôi, tớ', 'Là', 'Người', 'Không'],
          },
          {
            id: 'ex_1761712611318_mh5qh2n5h',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“是” có nghĩa là gì?',
            answer: 'Là',
            explanation: '“是” (shì) là động từ "to be", dùng để khẳng định.',
            options: ['Kêu, gọi, tên là', 'Là', 'Người', 'Cũng'],
          },
          {
            id: 'ex_1761712611318_hzjixpr5u',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: 'Từ nào có nghĩa là "Người"?',
            answer: '人',
            explanation: '“人” (rén) có nghĩa là con người.',
            options: ['人', '吗', '们', '也'],
          },
          {
            id: 'ex_1761712611318_wn720uqhn',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: 'Từ nào dùng để hỏi (trợ từ nghi vấn)?',
            answer: '吗',
            explanation:
              '“吗” (ma) là trợ từ đặt cuối câu để biến câu trần thuật thành câu hỏi Có/Không.',
            options: ['你', '好', '吗', '不'],
          },
          {
            id: 'ex_1761712611318_e1gctso2b',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“他” có nghĩa là gì?',
            answer: 'Anh ấy, ông ấy, nó',
            explanation: '“他” (tā) là đại từ nhân xưng ngôi thứ 3 số ít, dùng cho nam giới.',
            options: ['Anh ấy, ông ấy, nó', 'Cô ấy, chị ấy, bà ấy', 'Cũng, cũng vậy', 'Không'],
          },
          {
            id: 'ex_1761712611318_gld0dmnxg',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“不” có nghĩa là gì?',
            answer: 'Không',
            explanation: '“不” (bù) dùng để phủ định.',
            options: ['Tốt, khỏe', 'Là', 'Không', 'Cũng, cũng vậy'],
          },
          {
            id: 'ex_1761712611318_4ynxln2sr',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“日本” có nghĩa là gì?',
            answer: 'Nhật Bản',
            explanation: '“日本” (Rìběn) là quốc hiệu của Nhật Bản.',
            options: [
              'Pháp (nước Pháp)',
              'Canada',
              'Nhật Bản',
              'Ngài, ông, bà (ngôi thứ 2 lịch sự)',
            ],
          },
          {
            id: 'ex_1761712611318_nm9gfwbmx',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“法国” có nghĩa là gì?',
            answer: 'Pháp (nước Pháp)',
            explanation: '“法国” (Fǎguó) là quốc hiệu của nước Pháp.',
            options: ['Nhật Bản', 'Pháp (nước Pháp)', 'Canada', 'Giáo viên, thầy/cô giáo'],
          },
          {
            id: 'ex_1761712611318_1iw5jt1ci',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: 'Từ nào có nghĩa là "Canada"?',
            answer: '加拿大',
            explanation: '“加拿大” (Jiānádà) là quốc hiệu của Canada.',
            options: ['日本', '法国', '加拿大', '老师'],
          },
          {
            id: 'ex_1761712611318_y69wlnr8l',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: 'Hậu tố số nhiều (kết hợp với đại từ nhân xưng) là từ nào?',
            answer: '们',
            explanation:
              '“们” (men) thêm vào sau đại từ để tạo thành số nhiều (VD: 我们 - chúng tôi).',
            options: ['们', '也', '她', '人'],
          },
          {
            id: 'ex_1761712611318_0xaxohxbp',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“我们” có nghĩa là gì?',
            answer: 'Chúng tôi, chúng ta',
            explanation: '“我们” (wǒmen) có nghĩa là chúng tôi, chúng ta.',
            options: [
              'Chúng tôi, chúng ta',
              'Các bạn, các anh/chị',
              'Bọn họ (các cô ấy)',
              'Giáo viên, thầy/cô giáo',
            ],
          },
          {
            id: 'ex_1761712611318_xjqn0bjv1',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“你们” có nghĩa là gì?',
            answer: 'Các bạn, các anh/chị',
            explanation: '“你们” (nǐmen) là đại từ nhân xưng ngôi thứ 2 số nhiều.',
            options: [
              'Chúng tôi, chúng ta',
              'Các bạn, các anh/chị',
              'Bọn họ (cả nam nữ)',
              'Học sinh, sinh viên',
            ],
          },
          {
            id: 'ex_1761712611318_n9dqa8we7',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“他们” có nghĩa là gì?',
            answer: 'Bọn họ (cả nam nữ)',
            explanation:
              '“他们” (tāmen) là đại từ nhân xưng ngôi thứ 3 số nhiều, dùng chung cho cả nam và nữ.',
            options: [
              'Bọn họ (cả nam nữ)',
              'Bọn họ (các cô ấy)',
              'Học sinh, sinh viên',
              'Cũng, cũng vậy',
            ],
          },
          {
            id: 'ex_1761712611318_90oo7liyp',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“她们” dùng để chỉ ai?',
            answer: 'Bọn họ (các cô ấy)',
            explanation:
              '“她们” (tāmen) là đại từ nhân xưng ngôi thứ 3 số nhiều, dùng riêng cho nữ giới.',
            options: [
              'Bọn họ (cả nam nữ)',
              'Bọn họ (các cô ấy)',
              'Các bạn, các anh/chị',
              'Chúng tôi, chúng ta',
            ],
          },
          {
            id: 'ex_1761712611318_g1ztl8pcx',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: 'Từ nào có nghĩa là "Giáo viên, thầy/cô giáo"?',
            answer: '老师',
            explanation: '“老师” (lǎoshī) có nghĩa là giáo viên.',
            options: ['老师', '学生', '您', '她'],
          },
          {
            id: 'ex_1761712611318_s1igmicmj',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“您” có nghĩa là gì?',
            answer: 'Ngài, ông, bà',
            explanation:
              '“您” (nín) là đại từ nhân xưng ngôi thứ 2 số ít, mang sắc thái trang trọng, lịch sự.',
            options: ['Tôi, tớ', 'Bạn, anh, chị', 'Ngài, ông, bà', 'Cô ấy, chị ấy, bà ấy'],
          },
          {
            id: 'ex_1761712611318_dour6nk02',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“学生” có nghĩa là gì?',
            answer: 'Học sinh, sinh viên',
            explanation: '“学生” (xuésheng) có nghĩa là học sinh hoặc sinh viên.',
            options: [
              'Giáo viên, thầy/cô giáo',
              'Học sinh, sinh viên',
              'Ngài, ông, bà (ngôi thứ 2 lịch sự)',
              'Cô ấy, chị ấy, bà ấy (ngôi thứ 3 số ít,',
            ],
          },
          {
            id: 'ex_1761712611318_tifshnm2o',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“她” có nghĩa là gì?',
            answer: 'Cô ấy, chị ấy, bà ấy',
            explanation: '“她” (tā) là đại từ nhân xưng ngôi thứ 3 số ít, dùng cho nữ giới.',
            options: ['Anh ấy, ông ấy, nó', 'Cô ấy, chị ấy, bà ấy', 'Cũng, cũng vậy', 'Không'],
          },
          {
            id: 'ex_1761712611318_na65ztume',
            categoryId: 'category_1761712611318_ngonv7dgl',
            type: 'multiple_choice',
            question: '“也” có nghĩa là gì?',
            answer: 'Cũng, cũng vậy',
            explanation: '“也” (yě) dùng để diễn đạt ý "cũng", "cũng vậy".',
            options: ['Cũng, cũng vậy', 'Không', 'Là', 'Tốt, khỏe'],
          },
        ],
      },
      {
        id: 'category_1761712611318_0lmli1r11',
        lessonId: 'lesson_1761712611317_fetbwjtlg',
        type: 'review',
        name: 'Ôn tập',
        description: 'Bài tập Ôn tập',
        order: 4,
        exercises: [
          {
            id: 'ex_1761712611318_pcj3w05t6',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '你',
            answer: 'Bạn, anh, chị (ngôi thứ 2 số ít)',
            explanation: '',
            pinyin: 'nǐ',
          },
          {
            id: 'ex_1761712611318_0xgvnxx7j',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '好',
            answer: 'Tốt, khỏe',
            explanation: '',
            pinyin: 'hǎo',
          },
          {
            id: 'ex_1761712611318_enxz2x4p0',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '我',
            answer: 'Tôi, tớ (ngôi thứ 1 số ít)',
            explanation: '',
            pinyin: 'wǒ',
          },
          {
            id: 'ex_1761712611318_qrodzwygj',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '叫',
            answer: 'Kêu, gọi, tên là',
            explanation: '',
            pinyin: 'jiào',
          },
          {
            id: 'ex_1761712611318_k4mlofok8',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '是',
            answer: 'Là',
            explanation: '',
            pinyin: 'shì',
          },
          {
            id: 'ex_1761712611318_76ytcafzv',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '人',
            answer: 'Người',
            explanation: '',
            pinyin: 'rén',
          },
          {
            id: 'ex_1761712611318_8bh2ge6td',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '吗',
            answer: 'Trợ từ nghi vấn (đặt cuối câu)',
            explanation: '',
            pinyin: 'ma',
          },
          {
            id: 'ex_1761712611318_es6gkspb2',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '他',
            answer: 'Anh ấy, ông ấy, nó (ngôi thứ 3 số ít, giống đực)',
            explanation: '',
            pinyin: 'tā',
          },
          {
            id: 'ex_1761712611318_erz81y9pf',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '不',
            answer: 'Không',
            explanation: '',
            pinyin: 'bù',
          },
          {
            id: 'ex_1761712611318_15ynqt155',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '日本',
            answer: 'Nhật Bản',
            explanation: '',
            pinyin: 'Rìběn',
          },
          {
            id: 'ex_1761712611318_toqxrblrq',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '法国',
            answer: 'Pháp (nước Pháp)',
            explanation: '',
            pinyin: 'Fǎguó',
          },
          {
            id: 'ex_1761712611318_u3zbhv8qz',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '加拿大',
            answer: 'Canada',
            explanation: '',
            pinyin: 'Jiānádà',
          },
          {
            id: 'ex_1761712611318_g87u9d9cg',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '们',
            answer: 'Hậu tố số nhiều (kết hợp với đại từ nhân xưng)',
            explanation: '',
            pinyin: 'men',
          },
          {
            id: 'ex_1761712611318_4bfx5sr1f',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '我们',
            answer: 'Chúng tôi, chúng ta',
            explanation: '',
            pinyin: 'wǒmen',
          },
          {
            id: 'ex_1761712611318_brnvxh1y4',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '你们',
            answer: 'Các bạn, các anh/chị',
            explanation: '',
            pinyin: 'nǐmen',
          },
          {
            id: 'ex_1761712611318_qu199rera',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '他们',
            answer: 'Bọn họ (cả nam nữ)',
            explanation: '',
            pinyin: 'tāmen',
          },
          {
            id: 'ex_1761712611318_6dm7zkpv0',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '她们',
            answer: 'Bọn họ (các cô ấy)',
            explanation: '',
            pinyin: 'tāmen',
          },
          {
            id: 'ex_1761712611318_mvsns2alm',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '老师',
            answer: 'Giáo viên, thầy/cô giáo',
            explanation: '',
            pinyin: 'lǎoshī',
          },
          {
            id: 'ex_1761712611318_wua2a2izq',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '您',
            answer: 'Ngài, ông, bà (ngôi thứ 2 lịch sự)',
            explanation: '',
            pinyin: 'nín',
          },
          {
            id: 'ex_1761712611318_rt38fkxqr',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '学生',
            answer: 'Học sinh, sinh viên',
            explanation: '',
            pinyin: 'xuésheng',
          },
          {
            id: 'ex_1761712611318_zu1p29ziv',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '她',
            answer: 'Cô ấy, chị ấy, bà ấy (ngôi thứ 3 số ít,',
            explanation: '',
            pinyin: 'tā',
          },
          {
            id: 'ex_1761712611318_1p8oymezg',
            categoryId: 'category_1761712611318_0lmli1r11',
            type: 'flashcard',
            question: '也',
            answer: 'Cũng, cũng vậy',
            explanation: '',
            pinyin: 'yě',
          },
        ],
      },
      {
        id: 'category_1761712611318_t4ueko8y0',
        lessonId: 'lesson_1761712611317_fetbwjtlg',
        type: 'dialogue',
        name: 'Hội thoại',
        description: 'Bài tập Hội thoại',
        order: 5,
        exercises: [
          {
            id: 'dialogue_1761712611318_pksp8xutz',
            categoryId: 'category_1761712611318_t4ueko8y0',
            type: 'dialogue',
            context: 'Bài khóa 1',
            lines: [
              {
                speaker: '小明',
                text: '你好',
                pinyin: 'nǐ hǎo',
                translation: 'Xin chào',
              },
              {
                speaker: '小红',
                text: '你好',
                pinyin: 'nǐ hǎo',
                translation: 'Xin chào',
              },
              {
                speaker: '小明',
                text: '我叫小明',
                pinyin: 'wǒ jiào Xiǎo Míng',
                translation: 'Tôi tên là Tiểu Minh',
              },
              {
                speaker: '小红',
                text: '我叫小红',
                pinyin: 'wǒ jiào Xiǎo Hóng',
                translation: 'Tôi tên là Tiểu Hồng',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'lesson_1761712611318_a6kp2lzcz',
    name_zh: '',
    name_vi: '这是安妮的地图',
    description: 'Bài học 这是安妮的地图',
    order: 2,
    categories: [
      {
        id: 'category_1761712611318_lruu2doie',
        lessonId: 'lesson_1761712611318_a6kp2lzcz',
        type: 'vocabulary',
        name: 'Từ vựng',
        description: 'Bài tập Từ vựng',
        order: 1,
        exercises: [
          {
            id: 'ex_1761712611318_hjc9l1oqh',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '这',
            answer: 'cái này, đây',
            explanation: '',
            pinyin: 'zhè',
          },
          {
            id: 'ex_1761712611318_7b04t1o7h',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '的',
            answer: 'trợ từ (biểu thị sở hữu hoặc liên kết)',
            explanation: '',
            pinyin: 'de',
          },
          {
            id: 'ex_1761712611318_k6ndwxvbs',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '书',
            answer: 'sách',
            explanation: '',
            pinyin: 'shū',
          },
          {
            id: 'ex_1761712611318_m7glmd5do',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '词典',
            answer: 'từ điển',
            explanation: '',
            pinyin: 'cídiǎn',
          },
          {
            id: 'ex_1761712611318_k9d1fj1tw',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '地图',
            answer: 'bản đồ',
            explanation: '',
            pinyin: 'dìtú',
          },
          {
            id: 'ex_1761712611318_xcsrtg2t4',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '本子',
            answer: 'quyển vở',
            explanation: '',
            pinyin: 'běnzi',
          },
          {
            id: 'ex_1761712611318_6kkd9d9qn',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '笔',
            answer: 'bút',
            explanation: '',
            pinyin: 'bǐ',
          },
          {
            id: 'ex_1761712611318_w9my11b8j',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '有',
            answer: 'có',
            explanation: '',
            pinyin: 'yǒu',
          },
          {
            id: 'ex_1761712611318_rooz3v874',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '没有',
            answer: 'không có',
            explanation: '',
            pinyin: 'méiyǒu',
          },
          {
            id: 'ex_1761712611318_ya57qymqc',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '支',
            answer: 'cây (lượng từ cho bút, bút chì, v.v.)',
            explanation: '',
            pinyin: 'zhī',
          },
          {
            id: 'ex_1761712611318_qu6bzsxno',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '个',
            answer: 'cái (lượng từ chung)',
            explanation: '',
            pinyin: 'gè',
          },
          {
            id: 'ex_1761712611318_lt18o9za1',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '两',
            answer: 'hai',
            explanation: '',
            pinyin: 'liǎng',
          },
          {
            id: 'ex_1761712611318_c2mas6x2t',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '本',
            answer: 'quyển, cuốn (lượng từ cho sách, vở)',
            explanation: '',
            pinyin: 'běn',
          },
          {
            id: 'ex_1761712611318_9v1hoiovj',
            categoryId: 'category_1761712611318_lruu2doie',
            type: 'vocabulary',
            question: '张',
            answer: 'tờ, tấm (lượng từ cho giấy, ảnh, bàn...)',
            explanation: '',
            pinyin: 'zhāng',
          },
        ],
      },
      {
        id: 'category_1761712611318_hg76jlnj9',
        lessonId: 'lesson_1761712611318_a6kp2lzcz',
        type: 'grammar',
        name: 'Ngữ pháp',
        description: 'Bài tập Ngữ pháp',
        order: 2,
        exercises: [
          {
            id: 'ex_1761712611318_byyc82pd2',
            categoryId: 'category_1761712611318_hg76jlnj9',
            type: 'grammar',
            question: '1. Kết cấu trợ từ “的” dùng khi nào?',
            answer: 'Dùng sau định ngữ để biểu thị quan hệ sở hữu. ',
            explanation:
              'Cấu trúc: Định ngữ+ 的+ danh từ chính. “的” đứng sau thành phần định ngữ, giúp nối định ngữ với trung tâm ngữ, biểu thị mối quan hệ sở hữu hoặc thuộc về.',
            content: '这是大卫的书。zhè shì Dàwèi de shū. | 这是我的本子。zhè shì wǒ de běnzi.',
            examples: ['这是大卫的书。zhè shì Dàwèi de shū.'],
          },
          {
            id: 'ex_1761712611318_2s4v0l3t9',
            categoryId: 'category_1761712611318_hg76jlnj9',
            type: 'grammar',
            question: '2. Câu có động từ “有” dùng để làm gì?',
            answer: 'Dùng để biểu đạt ý “có”, “sở hữu”. Công thức: Chủ ngữ+有+danh từ',
            explanation:
              'Cấu trúc: Chủ ngữ+有+danh từ. “有” làm vị ngữ, dùng để biểu thị ai đó có cái gì.',
            content: '我有词典。wǒ yǒu cídiǎn. | 我有地图。wǒ yǒu dìtú.',
            examples: ['我有笔'],
          },
          {
            id: 'ex_1761712611318_msgkgvpb0',
            categoryId: 'category_1761712611318_hg76jlnj9',
            type: 'grammar',
            question: '3. Hình thức phủ định của câu “有” là gì?',
            answer: 'Là “没有”, không dùng “不有”.',
            explanation: 'Trong câu phủ định, “没有” được dùng thay cho “不有”.',
            content: '我没有地图。wǒ méiyǒu dìtú. ✓ | 我不有地图。wǒ bù yǒu dìtú. ✗',
            examples: ['我没有地图。wǒ méiyǒu dìtú.'],
          },
          {
            id: 'ex_1761712611318_nhqa1msqy',
            categoryId: 'category_1761712611318_hg76jlnj9',
            type: 'grammar',
            question: '4. Trong câu phủ định có dùng lượng từ không?',
            answer: 'Không dùng lượng từ trong câu phủ định với “没有”.',
            explanation: 'Khi dùng “没有”, không thêm cụm số + lượng từ trước tân ngữ.',
            content:
              '我没有词典。wǒ méiyǒu cídiǎn. ✓ | 我没有一本词典。wǒ méiyǒu yī běn cídiǎn. ✗ ',
            examples: ['我没有词典。wǒ méiyǒu cídiǎn.'],
          },
          {
            id: 'ex_1761712611318_yhig53j4r',
            categoryId: 'category_1761712611318_hg76jlnj9',
            type: 'grammar',
            question: '5. Khi nào dùng lượng từ (量词)?',
            answer: 'Dùng giữa số từ và danh từ.',
            explanation: 'Cấu trúc: Số  + Lượng từ + Danh từ',
            content: '一本书 yī běn shū | 两张地图 liǎng zhāng dìtú | 三支笔 sān zhī bǐ',
            examples: ['一本书 yī běn shū'],
          },
          {
            id: 'ex_1761712611318_76q69iwqx',
            categoryId: 'category_1761712611318_hg76jlnj9',
            type: 'grammar',
            question: '6. Các lượng từ cơ bản là gì?',
            answer: '本、张、支、个',
            explanation: 'Mỗi danh từ có lượng từ thích hợp riêng.',
            content:
              '本 → dùng cho sách, vở.  | 张 → dùng cho vật phẳng. | 支 → dùng cho vật dài, mảnh.  | 个 → dùng chung. ',
            examples: ['一本书 yī běn shū'],
          },
          {
            id: 'ex_1761712611318_p2rwi3tmp',
            categoryId: 'category_1761712611318_hg76jlnj9',
            type: 'grammar',
            question: '7. Khi nào dùng “两” và “二”?',
            answer: 'Dùng “两” trước lượng từ, không dùng “二”.',
            explanation: '“两” dùng trước lượng từ để chỉ số lượng.',
            content:
              '两个人 liǎng gè rén ✓ | 两本书 liǎng běn shū ✓ | 二个人 èr gè rén ✗ | 二本书 èr běn shū ✗',
            examples: ['两个人 liǎng gè rén'],
          },
        ],
      },
      {
        id: 'category_1761712611318_w0uhtrayf',
        lessonId: 'lesson_1761712611318_a6kp2lzcz',
        type: 'dialogue',
        name: 'Hội thoại',
        description: 'Bài tập Hội thoại',
        order: 3,
        exercises: [
          {
            id: 'dialogue_1761712611318_ju4v1l7f6',
            categoryId: 'category_1761712611318_w0uhtrayf',
            type: 'dialogue',
            context: 'Bài khoá 1',
            lines: [
              {
                speaker: '马丁',
                text: '大卫，这是你的书吗？',
                pinyin: 'Dàwèi, zhè shì nǐ de shū ma?',
                translation: 'Đại Vệ, đây là sách của cậu à?',
              },
              {
                speaker: '大卫',
                text: '是。',
                pinyin: 'Shì.',
                translation: 'Phải.',
              },
              {
                speaker: '马丁',
                text: '这是你的词典吗？',
                pinyin: 'Zhè shì nǐ de cídiǎn ma?',
                translation: 'Đây là từ điển của cậu à?',
              },
              {
                speaker: '大卫',
                text: '不是，这是山本的词典。',
                pinyin: 'Bù shì, zhè shì Shānběn de cídiǎn.',
                translation: 'Không phải, đây là từ điển của Shanben.',
              },
              {
                speaker: '马丁',
                text: '这是安妮的地图吗？',
                pinyin: 'Zhè shì Ānní de dìtú ma?',
                translation: 'Đây là bản đồ của Annie à?',
              },
              {
                speaker: '大卫',
                text: '是。马丁，这是你的本子吗？',
                pinyin: 'Shì. Mǎdīng, zhè shì nǐ de běnzi ma?',
                translation: 'Đúng. Martin, đây là vở của cậu à?',
              },
              {
                speaker: '马丁',
                text: '这是我的本子。这是山本的笔。',
                pinyin: 'Zhè shì wǒ de běnzi. Zhè shì Shānběn de bǐ.',
                translation: 'Đây là vở của tôi. Đây là bút của Shanben.',
              },
            ],
          },
          {
            id: 'dialogue_1761712611318_g4916vwrw',
            categoryId: 'category_1761712611318_w0uhtrayf',
            type: 'dialogue',
            context: 'Bài khoá 2',
            lines: [
              {
                speaker: '马丁',
                text: '大卫，你有本子吗？',
                pinyin: 'Dàwèi, nǐ yǒu běnzi ma?',
                translation: 'Đại Vệ, cậu có vở không?',
              },
              {
                speaker: '大卫',
                text: '有。',
                pinyin: 'Yǒu.',
                translation: 'Có.',
              },
              {
                speaker: '马丁',
                text: '你有词典吗？',
                pinyin: 'Nǐ yǒu cídiǎn ma?',
                translation: 'Cậu có từ điển không?',
              },
              {
                speaker: '大卫',
                text: '没有。',
                pinyin: 'Méiyǒu.',
                translation: 'Không có.',
              },
              {
                speaker: '马丁',
                text: '安妮有词典吗？',
                pinyin: 'Ānní yǒu cídiǎn ma?',
                translation: 'Annie có từ điển không?',
              },
              {
                speaker: '大卫',
                text: '她也没有词典。山本有词典。',
                pinyin: 'Tā yě méiyǒu cídiǎn. Shānběn yǒu cídiǎn.',
                translation: 'Cô ấy cũng không có từ điển. Shanben có.',
              },
            ],
          },
          {
            id: 'dialogue_1761712611318_09238ltng',
            categoryId: 'category_1761712611318_w0uhtrayf',
            type: 'dialogue',
            context: 'Bài khoá 3',
            lines: [
              {
                speaker: '小明',
                text: '安妮有一支笔，大卫有三个本子。他们没有词典，山本有两本词典。我有一张地图，安妮也有一张地图。这不是我的地图，是安妮的地图。',
                pinyin:
                  'Ānní yǒu yī zhī bǐ, Dàwèi yǒu sān gè běnzi.Tāmen méiyǒu cídiǎn, Shānběn yǒu liǎng běn cídiǎn.Wǒ yǒu yī zhāng dìtú, Ānní yě yǒu yī zhāng dìtú.Zhè bú shì wǒ de dìtú, shì Ānní de dìtú.',
                translation:
                  'Annie có một cây bút, Đại Vệ có ba quyển vở.Họ không có từ điển, Shanben có hai quyển từ điển.Tôi có một bản đồ, Annie cũng có một bản đồ.Đây không phải bản đồ của tôi, mà là của Annie.',
              },
            ],
          },
        ],
      },
      {
        id: 'category_1761712611318_vr2qs4uf3',
        lessonId: 'lesson_1761712611318_a6kp2lzcz',
        type: 'review',
        name: 'Ôn tập',
        description: 'Bài tập Ôn tập',
        order: 4,
        exercises: [
          {
            id: 'ex_1761712611318_n3f25ss08',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '这',
            answer: 'cái này, đây',
            explanation: '',
            pinyin: 'zhè',
          },
          {
            id: 'ex_1761712611318_poj708jdm',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '的',
            answer: 'trợ từ (biểu thị sở hữu hoặc liên kết)',
            explanation: '',
            pinyin: 'de',
          },
          {
            id: 'ex_1761712611318_gpaflmnt6',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '书',
            answer: 'sách',
            explanation: '',
            pinyin: 'shū',
          },
          {
            id: 'ex_1761712611318_u2d5xw8dq',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '词典',
            answer: 'từ điển',
            explanation: '',
            pinyin: 'cídiǎn',
          },
          {
            id: 'ex_1761712611318_uejyfqxo3',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '地图',
            answer: 'bản đồ',
            explanation: '',
            pinyin: 'dìtú',
          },
          {
            id: 'ex_1761712611318_oudzwg9a2',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '本子',
            answer: 'quyển vở',
            explanation: '',
            pinyin: 'běnzi',
          },
          {
            id: 'ex_1761712611318_te9ludfg3',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '笔',
            answer: 'bút',
            explanation: '',
            pinyin: 'bǐ',
          },
          {
            id: 'ex_1761712611318_2mplqcn1a',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '有',
            answer: 'có',
            explanation: '',
            pinyin: 'yǒu',
          },
          {
            id: 'ex_1761712611318_vu1su92j3',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '没有',
            answer: 'không có',
            explanation: '',
            pinyin: 'méiyǒu',
          },
          {
            id: 'ex_1761712611318_wwt8w7uft',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '支',
            answer: 'cây (lượng từ cho bút, bút chì, v.v.)',
            explanation: '',
            pinyin: 'zhī',
          },
          {
            id: 'ex_1761712611318_vsf9tjf5c',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '个',
            answer: 'cái (lượng từ chung)',
            explanation: '',
            pinyin: 'gè',
          },
          {
            id: 'ex_1761712611318_2uq26ct9y',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '两',
            answer: 'hai',
            explanation: '',
            pinyin: 'liǎng',
          },
          {
            id: 'ex_1761712611318_9d6rf256y',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '本',
            answer: 'quyển, cuốn (lượng từ cho sách, vở)',
            explanation: '',
            pinyin: 'běn',
          },
          {
            id: 'ex_1761712611318_93rxjbqfz',
            categoryId: 'category_1761712611318_vr2qs4uf3',
            type: 'flashcard',
            question: '张',
            answer: 'tờ, tấm (lượng từ cho giấy, ảnh, bàn...)',
            explanation: '',
            pinyin: 'zhāng',
          },
        ],
      },
      {
        id: 'category_1761712611318_3fpgnaigk',
        lessonId: 'lesson_1761712611318_a6kp2lzcz',
        type: 'writing',
        name: 'Luyện viết',
        description: 'Bài tập Luyện viết',
        order: 5,
        exercises: [
          {
            id: 'ex_1761712611318_eajoz4y3c',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '这',
            answer: 'cái này, đây',
            explanation: '',
            pinyin: 'zhè',
          },
          {
            id: 'ex_1761712611318_8m3b4c9zu',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '的',
            answer: 'trợ từ (biểu thị sở hữu hoặc liên kết)',
            explanation: '',
            pinyin: 'de',
          },
          {
            id: 'ex_1761712611318_ja2ipeshd',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '书',
            answer: 'sách',
            explanation: '',
            pinyin: 'shū',
          },
          {
            id: 'ex_1761712611318_p2uoq9qub',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '词典',
            answer: 'từ điển',
            explanation: '',
            pinyin: 'cídiǎn',
          },
          {
            id: 'ex_1761712611318_1mpzh1nsm',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '地图',
            answer: 'bản đồ',
            explanation: '',
            pinyin: 'dìtú',
          },
          {
            id: 'ex_1761712611318_9p69lfqjt',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '本子',
            answer: 'quyển vở',
            explanation: '',
            pinyin: 'běnzi',
          },
          {
            id: 'ex_1761712611318_g67la4lew',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '笔',
            answer: 'bút',
            explanation: '',
            pinyin: 'bǐ',
          },
          {
            id: 'ex_1761712611318_5okq9bl86',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '有',
            answer: 'có',
            explanation: '',
            pinyin: 'yǒu',
          },
          {
            id: 'ex_1761712611318_1klg6usvc',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '没有',
            answer: 'không có',
            explanation: '',
            pinyin: 'méiyǒu',
          },
          {
            id: 'ex_1761712611318_5rg7g0qd5',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '支',
            answer: 'cây (lượng từ cho bút, bút chì, v.v.)',
            explanation: '',
            pinyin: 'zhī',
          },
          {
            id: 'ex_1761712611318_bnvuugjlz',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '个',
            answer: 'cái (lượng từ chung)',
            explanation: '',
            pinyin: 'gè',
          },
          {
            id: 'ex_1761712611318_gdgw1zh0f',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '两',
            answer: 'hai',
            explanation: '',
            pinyin: 'liǎng',
          },
          {
            id: 'ex_1761712611318_6gt1ibvms',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '本',
            answer: 'quyển, cuốn (lượng từ cho sách, vở)',
            explanation: '',
            pinyin: 'běn',
          },
          {
            id: 'ex_1761712611318_opfhfs1sn',
            categoryId: 'category_1761712611318_3fpgnaigk',
            type: 'writing',
            question: '张',
            answer: 'tờ, tấm (lượng từ cho giấy, ảnh, bàn...)',
            explanation: '',
            pinyin: 'zhāng',
          },
        ],
      },
      {
        id: 'category_1761712611318_nxsm5s0nn',
        lessonId: 'lesson_1761712611318_a6kp2lzcz',
        type: 'test',
        name: 'Kiểm tra',
        description: 'Bài tập Kiểm tra',
        order: 6,
        exercises: [
          {
            id: 'ex_1761712611318_44uv7ibla',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“这” nghĩa là gì?',
            answer: 'Cái này, đây',
            explanation: '“这” (zhè) có nghĩa là “này”, dùng để chỉ sự vật gần người nói.',
            options: ['Cái này, đây', 'Của', 'Sách', 'Từ điển'],
          },
          {
            id: 'ex_1761712611318_h4h4hbwug',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“的” nghĩa là gì?',
            answer: 'Của',
            explanation: '“的” (de) là trợ từ biểu thị sở hữu, tương đương “của” trong tiếng Việt.',
            options: ['Của', 'Tốt', 'Hai', 'Có'],
          },
          {
            id: 'ex_1761712611318_79cjw02hm',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“书” nghĩa là gì?',
            answer: 'Sách',
            explanation: '“书” (shū) có nghĩa là “sách”.',
            options: ['Sách', 'Bút', 'Vở', 'Bản đồ'],
          },
          {
            id: 'ex_1761712611318_ck3rgvr11',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“词典” nghĩa là gì?',
            answer: 'Từ điển',
            explanation: '“词典” (cídiǎn) có nghĩa là “từ điển”.',
            options: ['Từ điển', 'Sách', 'Bản đồ', 'Vở'],
          },
          {
            id: 'ex_1761712611318_fi3v7e2c1',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“地图” nghĩa là gì?',
            answer: 'Bản đồ',
            explanation: '“地图” (dìtú) có nghĩa là “bản đồ”.',
            options: ['Bản đồ', 'Từ điển', 'Bút', 'Sách'],
          },
          {
            id: 'ex_1761712611318_i0z1kdm8f',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“本子” nghĩa là gì?',
            answer: 'Vở',
            explanation: '“本子” (běnzi) có nghĩa là “vở”, thường dùng để ghi chép.',
            options: ['Vở', 'Sách', 'Từ điển', 'Cái này'],
          },
          {
            id: 'ex_1761712611318_swmg4x83n',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“笔” nghĩa là gì?',
            answer: 'Bút',
            explanation: '“笔” (bǐ) có nghĩa là “bút”, dùng để viết.',
            options: ['Bút', 'Vở', 'Sách', 'Hai'],
          },
          {
            id: 'ex_1761712611318_33nzp44pq',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“有” nghĩa là gì?',
            answer: 'Có',
            explanation: '“有” (yǒu) có nghĩa là “có”, dùng để chỉ sự tồn tại hoặc sở hữu.',
            options: ['Có', 'Không có', 'Là', 'Hai'],
          },
          {
            id: 'ex_1761712611318_ijxu7rugu',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“没有” nghĩa là gì?',
            answer: 'Không có',
            explanation: '“没有” (méiyǒu) là dạng phủ định của “有”, nghĩa là “không có”.',
            options: ['Không có', 'Có', 'Là', 'Hai'],
          },
          {
            id: 'ex_1761712611318_oav8gor99',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“支” nghĩa là gì?',
            answer: 'Lượng từ cho vật dài (bút, bút chì...)',
            explanation: '“支” (zhī) là lượng từ dùng cho vật dài như bút, súng, nhánh cây...',
            options: [
              'Của',
              'Lượng từ cho vật phẳng',
              'Lượng từ cho sách',
              'Lượng từ cho vật dài (bút, bút chì...)',
            ],
          },
          {
            id: 'ex_1761712611318_piw237j4a',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“个” nghĩa là gì?',
            answer: 'Lượng từ chung',
            explanation: '“个” (gè) là lượng từ phổ biến nhất, dùng cho nhiều danh từ.',
            options: ['Lượng từ chung', 'Lượng từ cho vật phẳng', 'Lượng từ cho sách', 'Hai'],
          },
          {
            id: 'ex_1761712611318_6xcap8hdt',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“两” nghĩa là gì?',
            answer: 'Hai',
            explanation: '“两” (liǎng) nghĩa là “hai”, dùng trước lượng từ.',
            options: ['Hai', 'Ba', 'Một', 'Sách'],
          },
          {
            id: 'ex_1761712611318_0zuvptpxn',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“本” nghĩa là gì?',
            answer: 'Lượng từ cho sách, vở, từ điển',
            explanation: '“本” (běn) là lượng từ dùng cho sách, vở, từ điển.',
            options: [
              'Lượng từ cho vật phẳng',
              'Lượng từ cho sách, vở, từ điển',
              'Lượng từ cho vật dài',
              'Lượng từ chung',
            ],
          },
          {
            id: 'ex_1761712611318_92l1vcxep',
            categoryId: 'category_1761712611318_nxsm5s0nn',
            type: 'multiple_choice',
            question: '“张” nghĩa là gì?',
            answer: 'Lượng từ cho vật phẳng (giấy, ảnh, bản đồ...)',
            explanation: '“张” (zhāng) là lượng từ dùng cho vật phẳng như giấy, ảnh, bản đồ.',
            options: [
              'Hai',
              'Lượng từ cho sách',
              'Lượng từ cho vật dài',
              'Lượng từ cho vật phẳng (giấy, ảnh, bản đồ...)',
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'lesson_1761712611318_ekj5jqs15',
    name_zh: '',
    name_vi: '你家有几口人',
    description: 'Bài học 你家有几口人',
    order: 3,
    categories: [
      {
        id: 'category_1761712611318_epch0tplq',
        lessonId: 'lesson_1761712611318_ekj5jqs15',
        type: 'vocabulary',
        name: 'Từ vựng',
        description: 'Bài tập Từ vựng',
        order: 1,
        exercises: [
          {
            id: 'ex_1761712611318_t93uj3klj',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '什么',
            answer: 'gì / cái gì',
            explanation: '',
            pinyin: 'shénme',
          },
          {
            id: 'ex_1761712611318_sv6vi92k9',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '家',
            answer: 'nhà / gia đình',
            explanation: '',
            pinyin: 'jiā',
          },
          {
            id: 'ex_1761712611318_rsse913jv',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '照片',
            answer: 'ảnh / tấm ảnh',
            explanation: '',
            pinyin: 'zhàopiàn',
          },
          {
            id: 'ex_1761712611318_7xajuxclt',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '几',
            answer: 'mấy / bao nhiêu',
            explanation: '',
            pinyin: 'jǐ',
          },
          {
            id: 'ex_1761712611318_ntv10z5gv',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '口',
            answer: '(lượng từ dùng cho người trong gia đình) / miệng',
            explanation: '',
            pinyin: 'kǒu',
          },
          {
            id: 'ex_1761712611318_328k8p4wx',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '谁',
            answer: 'ai',
            explanation: '',
            pinyin: 'shéi',
          },
          {
            id: 'ex_1761712611318_cg6j3ipna',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '哥哥',
            answer: 'anh trai',
            explanation: '',
            pinyin: 'gēge',
          },
          {
            id: 'ex_1761712611318_9935oyvw7',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '爸爸',
            answer: 'bố / cha',
            explanation: '',
            pinyin: 'bàba',
          },
          {
            id: 'ex_1761712611318_ngiolus2h',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '妈妈',
            answer: 'mẹ',
            explanation: '',
            pinyin: 'māma',
          },
          {
            id: 'ex_1761712611318_8trc1q79j',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '姐姐',
            answer: 'chị gái',
            explanation: '',
            pinyin: 'jiějie',
          },
          {
            id: 'ex_1761712611318_t4lb0vvli',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '和',
            answer: 'và / cùng với',
            explanation: '',
            pinyin: 'hé',
          },
          {
            id: 'ex_1761712611318_fgrdjyopl',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '做',
            answer: 'làm / làm việc',
            explanation: '',
            pinyin: 'zuò',
          },
          {
            id: 'ex_1761712611318_tm5s4hvxd',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '工作',
            answer: 'công việc / làm việc',
            explanation: '',
            pinyin: 'gōngzuò',
          },
          {
            id: 'ex_1761712611318_bdd764ih3',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '妹妹',
            answer: 'em gái',
            explanation: '',
            pinyin: 'mèimei',
          },
          {
            id: 'ex_1761712611318_koxmpdptk',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '大夫',
            answer: 'bác sĩ',
            explanation: '',
            pinyin: 'dàifu',
          },
          {
            id: 'ex_1761712611318_mgd8hhz4p',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '全',
            answer: 'toàn bộ / tất cả',
            explanation: '',
            pinyin: 'quán',
          },
          {
            id: 'ex_1761712611318_cws9gh7ti',
            categoryId: 'category_1761712611318_epch0tplq',
            type: 'vocabulary',
            question: '弟弟',
            answer: 'em trai',
            explanation: '',
            pinyin: 'dìdi',
          },
        ],
      },
      {
        id: 'category_1761712611318_snpbokhlm',
        lessonId: 'lesson_1761712611318_ekj5jqs15',
        type: 'grammar',
        name: 'Ngữ pháp',
        description: 'Bài tập Ngữ pháp',
        order: 2,
        exercises: [
          {
            id: 'ex_1761712611318_k3c3qttpz',
            categoryId: 'category_1761712611318_snpbokhlm',
            type: 'grammar',
            question: '1. Câu hỏi sử dụng đại từ nghi vấn',
            answer: '谁 ai、几 mấy、什么 cái gì',
            explanation:
              'Cách dùng:Dùng để hỏi người; Khi làm định ngữ trong câu,  phía sau phải có trợ từ kết cấu “的”. |Dùng để hỏi số lượng nhỏ hơn 10, giữa danh từ và “几” thường phải thêm lượng từ phù hợp.|Chú ý: khi sử dụng đại từ nghi vấn để hỏi, cuối câu không được dùng trợ từ nghi vấn “吗” ',
            content:
              '这是谁的地图? 这是谁地图？x| 你家有几口人? V  这你家有几人？x｜这是什么吗？X 这是什么？V',
            examples: ['这是谁的书？'],
          },
          {
            id: 'ex_1761712611318_akukibom7',
            categoryId: 'category_1761712611318_snpbokhlm',
            type: 'grammar',
            question: '2. Đại từ nhân xưng làm định ngữ',
            answer:
              ' Đại từ nhân xưng làm định ngữ có thể biểu thị quan hệ sở hữu, phía sau phải thêm trợ từ kết cấu “的”，',
            explanation: 'Công thức: Đại từ nhân xứng+的+danh từ',
            content: '这是我的书。',
            examples: ['这是我的词典。'],
          },
        ],
      },
      {
        id: 'category_1761712611318_i9zvv6577',
        lessonId: 'lesson_1761712611318_ekj5jqs15',
        type: 'dialogue',
        name: 'Hội thoại',
        description: 'Bài tập Hội thoại',
        order: 3,
        exercises: [
          {
            id: 'dialogue_1761712611318_oxou2plu4',
            categoryId: 'category_1761712611318_i9zvv6577',
            type: 'dialogue',
            context: 'Bài khoá 1',
            lines: [
              {
                speaker: '小明',
                text: '马丁，这是什么？',
                pinyin: 'Mǎdīng, zhè shì shénme?',
                translation: 'Martin, đây là cái gì?',
              },
              {
                speaker: '马丁',
                text: '这是我家的照片。',
                pinyin: 'Zhè shì wǒ jiā de zhàopiàn.',
                translation: 'Đây là ảnh gia đình tôi.',
              },
              {
                speaker: '小明',
                text: '你家有几口人？',
                pinyin: 'Nǐ jiā yǒu jǐ kǒu rén?',
                translation: 'Nhà bạn có mấy người?',
              },
              {
                speaker: '马丁',
                text: '我家有四口人。',
                pinyin: 'Wǒ jiā yǒu sì kǒu rén.',
                translation: 'Nhà tôi có bốn người.',
              },
              {
                speaker: '小明',
                text: '他是谁？',
                pinyin: 'Tā shì shéi?',
                translation: 'Anh ấy là ai?',
              },
              {
                speaker: '马丁',
                text: '他是我哥哥。',
                pinyin: 'Tā shì wǒ gēge.',
                translation: 'Anh ấy là anh trai tôi.',
              },
            ],
          },
          {
            id: 'dialogue_1761712611318_znu0z69cc',
            categoryId: 'category_1761712611318_i9zvv6577',
            type: 'dialogue',
            context: 'Bài khoá 2',
            lines: [
              {
                speaker: '大卫',
                text: '山本，你家有几口人？',
                pinyin: 'Shānběn, nǐ jiā yǒu jǐ kǒu rén?',
                translation: 'Yamamoto, nhà bạn có mấy người?',
              },
              {
                speaker: '山本',
                text: '四口人：爸爸、妈妈、姐姐和我。',
                pinyin: 'Sì kǒu rén: bàba, māma, jiějie hé wǒ.',
                translation: 'Bốn người: bố, mẹ, chị gái và tôi.',
              },
              {
                speaker: '马丁',
                text: '你爸爸、妈妈做什么工作？',
                pinyin: 'Nǐ bàba, māma zuò shénme gōngzuò?',
                translation: 'Bố mẹ bạn làm nghề gì?',
              },
              {
                speaker: '大卫',
                text: '我爸爸是老师，妈妈不工作。',
                pinyin: 'Wǒ bàba shì lǎoshī, māma bù gōngzuò.',
                translation: 'Bố tôi là giáo viên, mẹ tôi không đi làm.',
              },
              {
                speaker: '马丁',
                text: '大卫，你家有几口人？',
                pinyin: 'Dàwèi, nǐ jiā yǒu jǐ kǒu rén?',
                translation: 'David, nhà bạn có mấy người?',
              },
              {
                speaker: '大卫',
                text: '我家也有四口人。',
                pinyin: 'Wǒ jiā yě yǒu sì kǒu rén.',
                translation: 'Nhà tôi cũng có bốn người.',
              },
              {
                speaker: '山本',
                text: '你妈妈工作吗？',
                pinyin: 'Nǐ māma gōngzuò ma?',
                translation: 'Mẹ bạn có đi làm không?',
              },
              {
                speaker: '大卫',
                text: '工作。她是大夫。',
                pinyin: 'Gōngzuò. Tā shì dàifu.',
                translation: 'Có, bà ấy là bác sĩ.',
              },
            ],
          },
          {
            id: 'dialogue_1761712611318_vhtr9ez33',
            categoryId: 'category_1761712611318_i9zvv6577',
            type: 'dialogue',
            context: 'Bài khoá 3',
            lines: [
              {
                speaker: '安妮',
                text: '你好！这是我们全家的照片。我家有三口人：爸爸、妈妈和我。我没有哥哥、姐姐，也没有弟弟、妹妹。我爸爸是老师，妈妈是大夫。我是学生。你家有几口人？你爸爸、妈妈做什么工作？你有全家的照片吗？',
                pinyin:
                  'Nǐ hǎo! Zhè shì wǒmen quán jiā de zhàopiàn. Wǒ jiā yǒu sān kǒu rén: bàba, māma hé wǒ. Wǒ méiyǒu gēge, jiějie, yě méiyǒu dìdi, mèimei. Wǒ bàba shì lǎoshī, māma shì dàifu. Wǒ shì xuéshēng. Nǐ jiā yǒu jǐ kǒu rén? Nǐ bàba, māma zuò shénme gōngzuò? Nǐ yǒu quán jiā de zhàopiàn ma?',
                translation:
                  'Xin chào! Đây là ảnh cả gia đình tôi. Nhà tôi có ba người: bố, mẹ và tôi. Tôi không có anh trai, chị gái, cũng không có em trai, em gái. Bố tôi là giáo viên, mẹ tôi là bác sĩ. Tôi là học sinh. Nhà bạn có mấy người? Bố mẹ bạn làm nghề gì? Bạn có ảnh gia đình không?',
              },
            ],
          },
        ],
      },
      {
        id: 'category_1761712611318_1iwkace3i',
        lessonId: 'lesson_1761712611318_ekj5jqs15',
        type: 'review',
        name: 'Ôn tập',
        description: 'Bài tập Ôn tập',
        order: 4,
        exercises: [
          {
            id: 'ex_1761712611318_3hds8inmx',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '什么',
            answer: 'gì / cái gì',
            explanation: '',
            pinyin: 'shénme',
          },
          {
            id: 'ex_1761712611318_g25mze2bq',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '家',
            answer: 'nhà / gia đình',
            explanation: '',
            pinyin: 'jiā',
          },
          {
            id: 'ex_1761712611318_09oh8e5sc',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '照片',
            answer: 'ảnh / tấm ảnh',
            explanation: '',
            pinyin: 'zhàopiàn',
          },
          {
            id: 'ex_1761712611318_0eevcts3r',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '几',
            answer: 'mấy / bao nhiêu',
            explanation: '',
            pinyin: 'jǐ',
          },
          {
            id: 'ex_1761712611318_scq1z9338',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '口',
            answer: '(lượng từ dùng cho người trong gia đình) / miệng',
            explanation: '',
            pinyin: 'kǒu',
          },
          {
            id: 'ex_1761712611318_9028edq9u',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '谁',
            answer: 'ai',
            explanation: '',
            pinyin: 'shéi',
          },
          {
            id: 'ex_1761712611318_rjqn4266z',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '哥哥',
            answer: 'anh trai',
            explanation: '',
            pinyin: 'gēge',
          },
          {
            id: 'ex_1761712611318_bs0c5daur',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '爸爸',
            answer: 'bố / cha',
            explanation: '',
            pinyin: 'bàba',
          },
          {
            id: 'ex_1761712611318_v3xnwfyjc',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '妈妈',
            answer: 'mẹ',
            explanation: '',
            pinyin: 'māma',
          },
          {
            id: 'ex_1761712611318_vjg9lwvhh',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '姐姐',
            answer: 'chị gái',
            explanation: '',
            pinyin: 'jiějie',
          },
          {
            id: 'ex_1761712611318_iguwla13j',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '和',
            answer: 'và / cùng với',
            explanation: '',
            pinyin: 'hé',
          },
          {
            id: 'ex_1761712611318_yicfot5xw',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '做',
            answer: 'làm / làm việc',
            explanation: '',
            pinyin: 'zuò',
          },
          {
            id: 'ex_1761712611318_rxoorzjl0',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '工作',
            answer: 'công việc / làm việc',
            explanation: '',
            pinyin: 'gōngzuò',
          },
          {
            id: 'ex_1761712611318_9te2uqthq',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '妹妹',
            answer: 'em gái',
            explanation: '',
            pinyin: 'mèimei',
          },
          {
            id: 'ex_1761712611318_to2n3hlm7',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '大夫',
            answer: 'bác sĩ',
            explanation: '',
            pinyin: 'dàifu',
          },
          {
            id: 'ex_1761712611318_0mq2qchy1',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '全',
            answer: 'toàn bộ / tất cả',
            explanation: '',
            pinyin: 'quán',
          },
          {
            id: 'ex_1761712611318_i35tosvpm',
            categoryId: 'category_1761712611318_1iwkace3i',
            type: 'flashcard',
            question: '弟弟',
            answer: 'em trai',
            explanation: '',
            pinyin: 'dìdi',
          },
        ],
      },
      {
        id: 'category_1761712611318_fkh9uon1r',
        lessonId: 'lesson_1761712611318_ekj5jqs15',
        type: 'writing',
        name: 'Luyện viết',
        description: 'Bài tập Luyện viết',
        order: 5,
        exercises: [
          {
            id: 'ex_1761712611318_i92gqr066',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '什么',
            answer: 'gì / cái gì',
            explanation: '',
            pinyin: 'shénme',
          },
          {
            id: 'ex_1761712611318_g5ks147c6',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '家',
            answer: 'nhà / gia đình',
            explanation: '',
            pinyin: 'jiā',
          },
          {
            id: 'ex_1761712611318_r6d14zzzr',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '照片',
            answer: 'ảnh / tấm ảnh',
            explanation: '',
            pinyin: 'zhàopiàn',
          },
          {
            id: 'ex_1761712611318_mi8gf3pi1',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '几',
            answer: 'mấy / bao nhiêu',
            explanation: '',
            pinyin: 'jǐ',
          },
          {
            id: 'ex_1761712611318_c7dywatlx',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '口',
            answer: '(lượng từ dùng cho người trong gia đình) / miệng',
            explanation: '',
            pinyin: 'kǒu',
          },
          {
            id: 'ex_1761712611318_osp0qdoub',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '谁',
            answer: 'ai',
            explanation: '',
            pinyin: 'shéi',
          },
          {
            id: 'ex_1761712611318_ruoxw1frc',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '哥哥',
            answer: 'anh trai',
            explanation: '',
            pinyin: 'gēge',
          },
          {
            id: 'ex_1761712611318_3e4tt9ue7',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '爸爸',
            answer: 'bố / cha',
            explanation: '',
            pinyin: 'bàba',
          },
          {
            id: 'ex_1761712611318_2gh335rpn',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '妈妈',
            answer: 'mẹ',
            explanation: '',
            pinyin: 'māma',
          },
          {
            id: 'ex_1761712611318_pewo3el0h',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '姐姐',
            answer: 'chị gái',
            explanation: '',
            pinyin: 'jiějie',
          },
          {
            id: 'ex_1761712611318_upbx6yy6t',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '和',
            answer: 'và / cùng với',
            explanation: '',
            pinyin: 'hé',
          },
          {
            id: 'ex_1761712611318_wmdjbqcbs',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '做',
            answer: 'làm / làm việc',
            explanation: '',
            pinyin: 'zuò',
          },
          {
            id: 'ex_1761712611318_x9i3l5022',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '工作',
            answer: 'công việc / làm việc',
            explanation: '',
            pinyin: 'gōngzuò',
          },
          {
            id: 'ex_1761712611318_bohnb7um5',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '妹妹',
            answer: 'em gái',
            explanation: '',
            pinyin: 'mèimei',
          },
          {
            id: 'ex_1761712611318_640vby7f4',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '大夫',
            answer: 'bác sĩ',
            explanation: '',
            pinyin: 'dàifu',
          },
          {
            id: 'ex_1761712611318_whwalgto5',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '全',
            answer: 'toàn bộ / tất cả',
            explanation: '',
            pinyin: 'quán',
          },
          {
            id: 'ex_1761712611318_edg4aub9m',
            categoryId: 'category_1761712611318_fkh9uon1r',
            type: 'writing',
            question: '弟弟',
            answer: 'em trai',
            explanation: '',
            pinyin: 'dìdi',
          },
        ],
      },
      {
        id: 'category_1761712611319_iixd2fvm6',
        lessonId: 'lesson_1761712611318_ekj5jqs15',
        type: 'test',
        name: 'Kiểm tra',
        description: 'Bài tập Kiểm tra',
        order: 6,
        exercises: [
          {
            id: 'ex_1761712611319_2q40t02f8',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“什么” nghĩa là gì?',
            answer: 'Gì, cái gì',
            explanation: '',
            options: ['Gì, cái gì', 'Ai', 'Cái gì'],
          },
          {
            id: 'ex_1761712611319_l8pymchb9',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“家” nghĩa là gì?',
            answer: 'Nhà, gia đình',
            explanation: '',
            options: ['Nhà, gia đình', 'Anh ấy', 'Cô ấy'],
          },
          {
            id: 'ex_1761712611319_32eypm3g8',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“照片” nghĩa là gì?',
            answer: 'Ảnh, tấm ảnh',
            explanation: '',
            options: ['Ảnh, tấm ảnh', 'Mấy', 'Bác sĩ'],
          },
          {
            id: 'ex_1761712611319_zy3zqinf0',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“几” nghĩa là gì?',
            answer: 'Mấy',
            explanation: '',
            options: ['Mấy', 'Ai', 'Gì'],
          },
          {
            id: 'ex_1761712611319_10iwdi1g2',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“口” nghĩa là gì?',
            answer: '(Lượng từ cho người trong gia đình), miệng',
            explanation: '',
            options: [
              '(Lượng từ cho người trong gia đình), miệng',
              'Lượng từ dùng cho bút',
              'Lượng từ dùng cho sách',
            ],
          },
          {
            id: 'ex_1761712611319_2tsvsilnr',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“谁” nghĩa là gì?',
            answer: 'Ai',
            explanation: '',
            options: ['Ai', 'Cái gì', 'Mấy'],
          },
          {
            id: 'ex_1761712611319_vaqfxuznr',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“哥哥” nghĩa là gì?',
            answer: 'Anh trai',
            explanation: '',
            options: ['Anh trai', 'Em trai', 'Chị gái'],
          },
          {
            id: 'ex_1761712611319_mcht0o191',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“爸爸” nghĩa là gì?',
            answer: 'Bố, cha',
            explanation: '',
            options: ['Bố, cha', 'Anh trai', 'Em trai'],
          },
          {
            id: 'ex_1761712611319_nbyrzc3jx',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“妈妈” nghĩa là gì?',
            answer: 'Mẹ',
            explanation: '',
            options: ['Mẹ', 'Chị gái', 'Em gái'],
          },
          {
            id: 'ex_1761712611319_i9f0wth08',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“姐姐” nghĩa là gì?',
            answer: 'Chị gái',
            explanation: '',
            options: ['Chị gái', 'Mẹ', 'Em gái'],
          },
          {
            id: 'ex_1761712611319_31wn3bsmv',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“和” nghĩa là gì?',
            answer: 'Và, cùng với',
            explanation: '',
            options: ['Và', 'ai', 'Làm'],
          },
          {
            id: 'ex_1761712611319_asg76edp9',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“做” nghĩa là gì?',
            answer: 'Làm',
            explanation: '',
            options: ['Làm', 'Toàn bộ', 'Gì'],
          },
          {
            id: 'ex_1761712611319_j2h3ew539',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“工作” nghĩa là gì?',
            answer: 'Công việc, làm việc',
            explanation: '',
            options: ['Công việc, làm việc', 'Nhà', 'Tấm ảnh'],
          },
          {
            id: 'ex_1761712611319_utysvryob',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“妹妹” nghĩa là gì?',
            answer: 'Em gái',
            explanation: '',
            options: ['Em gái', 'Chị gái', 'Anh trai'],
          },
          {
            id: 'ex_1761712611319_z2fl9hm3i',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“大夫” nghĩa là gì?',
            answer: 'Bác sĩ',
            explanation: '',
            options: ['Bác sĩ', 'Cô giáo', 'Công nhân'],
          },
          {
            id: 'ex_1761712611319_myd9fdfgl',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“全” nghĩa là gì?',
            answer: 'Toàn bộ, tất cả',
            explanation: '',
            options: ['Toàn bộ, tất cả', 'Nhà', 'Công việc'],
          },
          {
            id: 'ex_1761712611319_16u52we6t',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'multiple_choice',
            question: '“弟弟” nghĩa là gì?',
            answer: 'Em trai',
            explanation: '',
            options: ['Em trai', 'Anh trai', 'Chị gái'],
          },
          {
            id: 'ex_1761712611319_n52qjk03y',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Xin chào! Đây là gì?',
            answer: '你好！这是什么？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_guvcngf0c',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Nhà tôi có 3 người: bố, mẹ và tôi.',
            answer: '我家有三口人：爸爸、妈妈和我。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_wos06bxme',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Tôi không có anh, chị, em trai hay em gái.',
            answer: '我没有哥哥、姐姐，也没有弟弟、妹妹。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_dich3tkqq',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Bố tôi là giáo viên, mẹ là bác sĩ, tôi là học sinh.',
            answer: '我爸爸是老师，妈妈是大夫。我是学生。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_tpd0zkfak',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Nhà bạn có mấy người?',
            answer: '你家有几口人？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_is813hznq',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Nhà tôi cũng có 4 người.',
            answer: '我家也有四口人。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_hfuodrx1m',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Tôi không có chị gái, tôi có một em gái.',
            answer: '我没有姐姐，我有一个妹妹。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_38v80iwem',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Anh ấy là ai?',
            answer: '他是谁？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_14la7l3xv',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Anh ấy là anh trai tôi.',
            answer: '他是我哥哥。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_c0y7ppjjt',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Mẹ bạn có làm việc không?',
            answer: '你妈妈工作吗？工作，她是大夫。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_w9jalekbs',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Đây là ảnh gì?',
            answer: '这是什么照片。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_jg5uw64gx',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Nhà bạn có mấy người?',
            answer: '你家有几口人？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_4d9f5tcdr',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Bốn người: bố, mẹ, chị gái và tôi.',
            answer: '四口人：爸爸、妈妈、姐姐和我。',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_ifvufpr69',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Bố bạn làm nghề gì?',
            answer: '你爸爸做什么工作？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_hc5dpuc25',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Mẹ bạn có làm việc không?',
            answer: '你妈妈工作吗？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_e1md7ah2l',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Bạn có anh chị em không?',
            answer: '你有哥哥姐姐妹妹吗？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_axfsd7dpz',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Anh ấy là ai?',
            answer: '他是谁？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_h5flsdwnq',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Anh ấy có sách không ?',
            answer: '他有书吗？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_ciasatnf5',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Bạn là học sinh đúng không?',
            answer: '你是学生吗？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
          {
            id: 'ex_1761712611319_5c2iyhz0w',
            categoryId: 'category_1761712611319_iixd2fvm6',
            type: 'input',
            question: 'Bạn có toàn bộ ảnh gia đình không?',
            answer: '你有全家的照片吗？',
            explanation: '',
            placeholder: 'Nhập đáp án',
          },
        ],
      },
    ],
  },
];
